import { useEffect, useMemo, useState } from 'react'
import { createMentor, deleteMentor, getMentors, updateMentor } from './api.js'

const statusOptions = ['Active', 'Away', 'Suspended']
const fields = [['name', 'Full Name', 'text'], ['email', 'Email / Contact', 'email'], ['participants', 'Participants', 'number'], ['status', 'Status', 'select']]

function MentorSection({ notify, onBack }) {
  const [data, setData] = useState([])
  const [loading, setLoading] = useState(true)
  const [requestError, setRequestError] = useState('')
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('All')
  const [modal, setModal] = useState(null)
  const filtered = useMemo(() => data.filter((mentor) => `${mentor.name} ${mentor.email}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All' || mentor.status === status)), [data, query, status])

  async function refresh() { setLoading(true); setRequestError(''); try { const response = await getMentors(); setData(response.data || []) } catch (error) { setRequestError(error.message) } finally { setLoading(false) } }
  useEffect(() => { let cancelled = false; getMentors().then((response) => { if (!cancelled) setData(response.data || []) }).catch((error) => { if (!cancelled) setRequestError(error.message) }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true } }, [])
  async function save(form) { try { if (modal.item) await updateMentor(modal.item.id, form); else await createMentor(form); await refresh(); setModal(null); notify(`Mentor ${modal.item ? 'updated' : 'added'} successfully.`) } catch (error) { return { error: error.message } } return null }
  async function remove(mentor) { if (!window.confirm(`Delete ${mentor.name}?`)) return; try { await deleteMentor(mentor.id); await refresh(); notify('Mentor deleted successfully.') } catch (error) { setRequestError(error.message) } }
  function resetFilters() { setQuery(''); setStatus('All') }

  return <><div className="participant-heading mentor-heading"><div><button className="admin-back-link" type="button" onClick={onBack}>← Back to Dashboard</button><span className="admin-kicker">MANAGEMENT / MENTORS</span><h1>Mentors</h1><p>Manage mentor coverage, availability, and participant assignments.</p></div><button className="admin-primary" type="button" onClick={() => setModal({ item: null })}>＋ Add Mentor</button></div>{requestError && <div className="participant-api-error" role="alert">{requestError} <button type="button" onClick={refresh}>Retry</button></div>}<div className="table-toolbar participant-filters"><label className="search-field"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name or email..." aria-label="Search mentors" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter mentors by status"><option>All</option>{statusOptions.map((option) => <option key={option}>{option}</option>)}</select><button className="filter-reset" type="button" onClick={resetFilters}>Reset filters</button><span className="result-count">{filtered.length} of {data.length}</span></div><div className="admin-table-wrap">{loading ? <div className="participant-loading">Loading mentors...</div> : <><table className="admin-table mentors-table"><thead><tr><th>Name</th><th>Email / Contact</th><th>Participants</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((mentor) => <tr key={mentor.id}><td><strong className="table-name"><span className="table-avatar">{mentor.name.slice(0, 2).toUpperCase()}</span>{mentor.name}</strong></td><td>{mentor.email}</td><td>{mentor.participants || 0}</td><td><span className={`status-pill ${mentor.status.toLowerCase()}`}>{mentor.status}</span></td><td><div className="table-actions"><button type="button" onClick={() => setModal({ item: mentor, view: true })}>View</button><button type="button" onClick={() => setModal({ item: mentor })}>Edit</button><button type="button" onClick={() => remove(mentor)}>Delete</button></div></td></tr>)}</tbody></table>{!filtered.length && <div className="empty-state"><strong>No mentors found</strong><span>Try changing your search or filters.</span><button className="admin-secondary" type="button" onClick={resetFilters}>Reset filters</button></div>}</>}</div>{modal && (modal.view ? <MentorDetails mentor={modal.item} onClose={() => setModal(null)} /> : <MentorModal item={modal.item} onClose={() => setModal(null)} onSave={save} />)}</>
}

function MentorModal({ item, onClose, onSave }) { const [form, setForm] = useState(() => item || { name: '', email: '', participants: 0, status: 'Active' }); const [error, setError] = useState(''); function update(field, value) { setForm((current) => ({ ...current, [field]: value })) } async function submit(event) { event.preventDefault(); if (!form.name.trim() || !form.email.trim()) { setError('Full Name and Email are required.'); return } if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim())) { setError('Enter a valid mentor email address.'); return } if (!statusOptions.includes(form.status)) { setError('Select a valid mentor status.'); return } const saveError = await onSave(form); if (saveError) setError(saveError.error) } return <div className="modal-backdrop"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="mentor-modal-title"><div className="modal-heading"><div><span className="admin-kicker">MENTOR RECORD</span><h2 id="mentor-modal-title">{item ? 'Edit Mentor' : 'Add Mentor'}</h2></div><button type="button" onClick={onClose} aria-label="Close mentor form">×</button></div><form onSubmit={submit}>{fields.map(([field, label, type]) => <label className="modal-field" key={field}><span>{label}{['name', 'email'].includes(field) ? ' *' : ''}</span>{type === 'select' ? <select value={form[field]} onChange={(event) => update(field, event.target.value)}>{statusOptions.map((option) => <option key={option}>{option}</option>)}</select> : <input type={type} min={type === 'number' ? 0 : undefined} required={['name', 'email'].includes(field)} value={form[field] ?? ''} onChange={(event) => update(field, event.target.value)} />}</label>)}{error && <span className="field-error" role="alert">{error}</span>}<div className="modal-actions"><button type="button" className="admin-secondary" onClick={onClose}>Cancel</button><button type="submit" className="admin-primary">Save mentor</button></div></form></section></div> }

function MentorDetails({ mentor, onClose }) { return <div className="modal-backdrop"><section className="admin-modal participant-details" role="dialog" aria-modal="true" aria-labelledby="mentor-details-title"><div className="modal-heading"><div><span className="admin-kicker">MENTOR DETAILS</span><h2 id="mentor-details-title">{mentor.name}</h2></div><button type="button" onClick={onClose} aria-label="Close mentor details">×</button></div><div className="details-avatar">{mentor.name.slice(0, 2).toUpperCase()}</div><dl><div><dt>Email / Contact</dt><dd>{mentor.email}</dd></div><div><dt>Participants</dt><dd>{mentor.participants || 0}</dd></div><div><dt>Status</dt><dd><span className={`status-pill ${mentor.status.toLowerCase()}`}>{mentor.status}</span></dd></div></dl><button className="admin-secondary" type="button" onClick={onClose}>Close details</button></section></div> }

export default MentorSection
