import { useEffect, useMemo, useState } from 'react'
import { createOrganizer, deleteOrganizer, getOrganizers, updateOrganizer } from './api.js'

const statusOptions = ['Active', 'Pending', 'Suspended']
const fields = [['name', 'Full Name', 'text'], ['email', 'Email / Contact', 'email'], ['organization', 'Organization', 'text'], ['events', 'Events Managed', 'number'], ['status', 'Status', 'select']]

function OrganizerSection({ notify, onBack }) {
  const [data, setData] = useState([])
  const [loading, setLoading] = useState(true)
  const [requestError, setRequestError] = useState('')
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('All')
  const [organization, setOrganization] = useState('All')
  const [modal, setModal] = useState(null)
  const organizations = [...new Set(data.map((organizer) => organizer.organization).filter(Boolean))]
  const filtered = useMemo(() => data.filter((organizer) => `${organizer.name} ${organizer.email} ${organizer.organization || ''}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All' || organizer.status === status) && (organization === 'All' || organizer.organization === organization)), [data, organization, query, status])

  async function refresh() { setLoading(true); setRequestError(''); try { const response = await getOrganizers(); setData(response.data || []) } catch (error) { setRequestError(error.message) } finally { setLoading(false) } }
  useEffect(() => { let cancelled = false; getOrganizers().then((response) => { if (!cancelled) setData(response.data || []) }).catch((error) => { if (!cancelled) setRequestError(error.message) }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true } }, [])
  async function save(form) { try { if (modal.item) await updateOrganizer(modal.item.id, form); else await createOrganizer(form); await refresh(); setModal(null); notify(`Organizer ${modal.item ? 'updated' : 'added'} successfully.`) } catch (error) { return { error: error.message } } return null }
  async function remove(organizer) { if (!window.confirm(`Delete ${organizer.name}?`)) return; try { await deleteOrganizer(organizer.id); await refresh(); notify('Organizer deleted successfully.') } catch (error) { setRequestError(error.message) } }
  function resetFilters() { setQuery(''); setStatus('All'); setOrganization('All') }

  return <><div className="participant-heading organizer-heading"><div><button className="admin-back-link" type="button" onClick={onBack}>← Back to Dashboard</button><span className="admin-kicker">MANAGEMENT / ORGANIZERS</span><h1>Organizers</h1><p>Manage event owners, organizations, and access status.</p></div><button className="admin-primary" type="button" onClick={() => setModal({ item: null })}>＋ Add Organizer</button></div>{requestError && <div className="participant-api-error" role="alert">{requestError} <button type="button" onClick={refresh}>Retry</button></div>}<div className="table-toolbar participant-filters"><label className="search-field"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email, or organization..." aria-label="Search organizers" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter organizers by status"><option>All</option>{statusOptions.map((option) => <option key={option}>{option}</option>)}</select><select value={organization} onChange={(event) => setOrganization(event.target.value)} aria-label="Filter organizers by organization"><option value="All">All organizations</option>{organizations.map((item) => <option key={item}>{item}</option>)}</select><button className="filter-reset" type="button" onClick={resetFilters}>Reset filters</button><span className="result-count">{filtered.length} of {data.length}</span></div><div className="admin-table-wrap">{loading ? <div className="participant-loading">Loading organizers...</div> : <><table className="admin-table organizers-table"><thead><tr><th>Name</th><th>Email / Contact</th><th>Organization</th><th>Events Managed</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((organizer) => <tr key={organizer.id}><td><strong className="table-name"><span className="table-avatar">{organizer.name.slice(0, 2).toUpperCase()}</span>{organizer.name}</strong></td><td>{organizer.email}</td><td>{organizer.organization || 'Not assigned'}</td><td>{organizer.events || 0}</td><td><span className={`status-pill ${organizer.status.toLowerCase()}`}>{organizer.status}</span></td><td><div className="table-actions"><button type="button" onClick={() => setModal({ item: organizer, view: true })}>View</button><button type="button" onClick={() => setModal({ item: organizer })}>Edit</button><button type="button" onClick={() => remove(organizer)}>Delete</button></div></td></tr>)}</tbody></table>{!filtered.length && <div className="empty-state"><strong>No organizers found</strong><span>Try changing your search or filters.</span><button className="admin-secondary" type="button" onClick={resetFilters}>Reset filters</button></div>}</>}</div>{modal && (modal.view ? <OrganizerDetails organizer={modal.item} onClose={() => setModal(null)} /> : <OrganizerModal item={modal.item} onClose={() => setModal(null)} onSave={save} />)}</>
}

function OrganizerModal({ item, onClose, onSave }) { const [form, setForm] = useState(() => item || { name: '', email: '', organization: '', events: 0, status: 'Active' }); const [error, setError] = useState(''); function update(field, value) { setForm((current) => ({ ...current, [field]: value })) } async function submit(event) { event.preventDefault(); if (!form.name.trim() || !form.email.trim() || !form.organization.trim()) { setError('Full Name, Email, and Organization are required.'); return } if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim())) { setError('Enter a valid organizer email address.'); return } if (!statusOptions.includes(form.status)) { setError('Select a valid organizer status.'); return } const saveError = await onSave(form); if (saveError) setError(saveError.error) } return <div className="modal-backdrop"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="organizer-modal-title"><div className="modal-heading"><div><span className="admin-kicker">ORGANIZER RECORD</span><h2 id="organizer-modal-title">{item ? 'Edit Organizer' : 'Add Organizer'}</h2></div><button type="button" onClick={onClose} aria-label="Close organizer form">×</button></div><form onSubmit={submit}>{fields.map(([field, label, type]) => <label className="modal-field" key={field}><span>{label}{['name', 'email', 'organization'].includes(field) ? ' *' : ''}</span>{type === 'select' ? <select value={form[field]} onChange={(event) => update(field, event.target.value)}>{statusOptions.map((option) => <option key={option}>{option}</option>)}</select> : <input type={type} min={type === 'number' ? 0 : undefined} required={['name', 'email', 'organization'].includes(field)} value={form[field] ?? ''} onChange={(event) => update(field, event.target.value)} />}</label>)}{error && <span className="field-error" role="alert">{error}</span>}<div className="modal-actions"><button type="button" className="admin-secondary" onClick={onClose}>Cancel</button><button type="submit" className="admin-primary">Save organizer</button></div></form></section></div> }

function OrganizerDetails({ organizer, onClose }) { return <div className="modal-backdrop"><section className="admin-modal participant-details" role="dialog" aria-modal="true" aria-labelledby="organizer-details-title"><div className="modal-heading"><div><span className="admin-kicker">ORGANIZER DETAILS</span><h2 id="organizer-details-title">{organizer.name}</h2></div><button type="button" onClick={onClose} aria-label="Close organizer details">×</button></div><div className="details-avatar">{organizer.name.slice(0, 2).toUpperCase()}</div><dl><div><dt>Email / Contact</dt><dd>{organizer.email}</dd></div><div><dt>Organization</dt><dd>{organizer.organization || 'Not assigned'}</dd></div><div><dt>Events managed</dt><dd>{organizer.events || 0}</dd></div><div><dt>Status</dt><dd><span className={`status-pill ${organizer.status.toLowerCase()}`}>{organizer.status}</span></dd></div></dl><button className="admin-secondary" type="button" onClick={onClose}>Close details</button></section></div> }

export default OrganizerSection
